services:
 spark-master:
   build: .
   image: my-spark-image
   ports:
     - "7077:7077"
     - "8080:8080"
   environment:
     - AWS_ACCESS_KEY_ID=your_access_key_id
     - AWS_SECRET_ACCESS_KEY=your_secret_access_key
   command: ["/opt/bitnami/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]


 spark-worker:
   build: .
   image: my-spark-image
   depends_on:
     - spark-master
   environment:
     - AWS_ACCESS_KEY_ID=your_access_key_id
     - AWS_SECRET_ACCESS_KEY=your_secret_access_key
     - SPARK_MASTER_URL=spark://spark-master:7077
